import { applyFilmLook } from "./apply.js";
import type { FilmLookConfig } from "./config.js";
import { createImage } from "./image.js";

/**
 * The look as a 3D LUT, so it can be a real effect inside After Effects.
 *
 * A bake in a panel is an engine, not a tool. What an artist wants is
 * something they drag onto a layer, that plays live, that keyframes, and that
 * renders with the comp — and for the tonal half of this chain that is exactly
 * what a `.cube` is.
 *
 * The chain divides cleanly. Exposure, both tonemaps, stock colour, the grade,
 * temperature and tint, CDL, split tone, bleach and fade are all per-pixel:
 * one colour in, one colour out, no neighbours consulted. That is the
 * definition of what a 3D LUT can represent, and it is also the half that
 * carries the look's character. The spatial stages — grain, halation, vignette,
 * bloom, distortion — cannot be a LUT at any size, because they depend on where
 * a pixel is and what is next to it.
 *
 * ## Why there is no shaper LUT here
 *
 * A tonemap normally consumes scene-linear values above 1.0, and a plain 0..1
 * cube would clamp them. That problem does not arise: the input is an image
 * After Effects has already rendered, so it is display-referred sRGB in 0..1.
 * The chain linearises internally, tonemaps, and encodes back before any of
 * the display-space stages run. Domain in, domain out, both [0,1].
 *
 * The one case it does not cover is a 32-bit float comp carrying values above
 * 1.0 — those clip at the LUT's edge. Worth knowing before grading a comp full
 * of blown highlights through one.
 */
export interface CubeOptions {
  /** Samples per axis. 33 is the usual choice and what most tools expect. */
  size?: number;
  /** Written into the file as a comment, so a stray .cube can be identified. */
  title?: string;
}

/**
 * Builds the per-pixel half of a config as a `.cube`.
 *
 * The lattice is run through the real chain rather than a reimplementation of
 * it: each entry is a one-pixel image, so there is exactly one definition of
 * what the look does and the LUT cannot drift away from the bake.
 */
export function buildCubeLut(
  config: FilmLookConfig,
  options: CubeOptions = {},
): string {
  const size = options.size ?? 33;
  if (size < 2 || size > 64) {
    throw new Error(`cube size must be between 2 and 64, got ${size}`);
  }

  /*
   * Spatial stages off, and grain in particular. A LUT is a colour mapping;
   * grain sampled into one would become a fixed pattern applied identically to
   * every frame, which is exactly the "dirt on the lens" the chain works to
   * avoid. It stays in the bake, or in a real grain effect on the layer.
   */
  const perPixel: FilmLookConfig = {
    ...config,
    grain_enable: false,
    grain_scale: 0,
    distortion_k1: 0,
    distortion_k2: 0,
    ca_lateral: 0,
    vignette: 0,
    vignette_mech: 0,
    bloom: 0,
    glare_intensity: 0,
    halation_scale: 0,
    diffusion: 0,
    anamorphic: 0,
    dehalo: 0,
    clarity: 0,
    sharpen: 0,
    chroma_denoise: 0,
    auto_levels: 0,
    letterbox: false,
  };

  /*
   * One image holding the whole lattice, in the order .cube expects: red
   * fastest, then green, then blue. Running it as a single image rather than
   * size³ one-pixel calls keeps this fast enough to regenerate on every slider
   * move — 33³ is 35,937 samples.
   */
  const total = size * size * size;
  const lattice = createImage(total, 1);
  let i = 0;
  for (let b = 0; b < size; b++) {
    for (let g = 0; g < size; g++) {
      for (let r = 0; r < size; r++) {
        lattice.data[i] = r / (size - 1);
        lattice.data[i + 1] = g / (size - 1);
        lattice.data[i + 2] = b / (size - 1);
        lattice.data[i + 3] = 1;
        i += 4;
      }
    }
  }

  const { image } = applyFilmLook(lattice, perPixel);

  const lines: string[] = [];
  lines.push(`# ${options.title ?? "SEED film look"}`);
  lines.push("# Generated by SEED / AE. The tonal half of the look only —");
  lines.push("# grain, halation, vignette and distortion are spatial and are");
  lines.push("# not representable in a colour lookup at any size.");
  lines.push(`LUT_3D_SIZE ${size}`);
  lines.push("DOMAIN_MIN 0.0 0.0 0.0");
  lines.push("DOMAIN_MAX 1.0 1.0 1.0");

  for (let p = 0; p < total; p++) {
    const o = p * 4;
    lines.push(
      `${fixed(image.data[o]!)} ${fixed(image.data[o + 1]!)} ${fixed(image.data[o + 2]!)}`,
    );
  }

  return lines.join("\n") + "\n";
}

/** Six decimals: below the precision of any host that reads these. */
function fixed(value: number): string {
  const clamped = value < 0 ? 0 : value > 1 ? 1 : value;
  return clamped.toFixed(6);
}

/**
 * Which stages a LUT cannot carry, for a given config.
 *
 * The panel says this out loud rather than letting an artist discover that
 * their grain never arrived. Only stages that are actually doing something in
 * this config are listed — naming a stage that is switched off would be noise.
 */
export function stagesLeftBehind(config: FilmLookConfig): string[] {
  const missing: string[] = [];
  if (config.grain_enable && config.grain_scale > 0) missing.push("grain");
  if (config.vignette > 0 || config.vignette_mech > 0) missing.push("vignette");
  if (config.halation_scale > 0) missing.push("halation");
  if (config.distortion_k1 !== 0 || config.distortion_k2 !== 0) {
    missing.push("distortion");
  }
  if (config.ca_lateral !== 0) missing.push("chromatic aberration");
  if (config.bloom > 0) missing.push("bloom");
  if (config.glare_intensity > 0) missing.push("glare");
  if (config.diffusion > 0) missing.push("diffusion");
  if (config.anamorphic > 0) missing.push("anamorphic streak");
  if (config.clarity !== 0) missing.push("clarity");
  if (config.sharpen > 0) missing.push("sharpen");
  if (config.chroma_denoise > 0) missing.push("chroma denoise");
  if (config.dehalo > 0) missing.push("dehalo");
  return missing;
}
