/**
 * Writes the vectors the C++ core is checked against.
 *
 * Two implementations of one look is a promise to keep them identical, and the
 * only way to keep it is to check. The TypeScript engine is the reference
 * because it is the one with the golden config behind it, so these are
 * generated from it rather than hand-written on either side.
 *
 *   npx tsx scripts/filmlook-vectors.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  applyFilmLook,
  createImage,
  resolveConfig,
  srgbToLinear,
  whitepointTonemap,
  type FloatImage,
} from "@seed-ae/filmlook";

const config = resolveConfig({ preset: "show-match", intensity: 1 });

/** A small deterministic picture, structured enough to exercise the optics. */
function picture(width: number, height: number): FloatImage {
  const image = createImage(width, height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const u = x / (width - 1);
      const v = y / (height - 1);
      const i = (y * width + x) * 4;
      const d = Math.hypot(u - 0.3, v - 0.3);
      const spot = Math.max(0, 1 - (d / 0.22) ** 2);
      image.data[i] = Math.min(1, u * 0.8 + spot);
      image.data[i + 1] = Math.min(1, v * 0.7 + spot);
      image.data[i + 2] = Math.min(1, (1 - u) * 0.6 + spot);
      image.data[i + 3] = 1;
    }
  }
  return image;
}

const WIDTH = 24;
const HEIGHT = 16;
const source = picture(WIDTH, HEIGHT);
const treated = applyFilmLook(
  { ...source, data: new Float32Array(source.data) },
  config,
  { frame: 3 },
).image;

const vectors = {
  note: "Generated by scripts/filmlook-vectors.ts. Do not edit by hand.",
  preset: "show-match",
  intensity: 1,
  frame: 3,
  width: WIDTH,
  height: HEIGHT,
  scalars: {
    srgbToLinear: [0.02, 0.18, 0.5, 1].map((v) => srgbToLinear(v)),
    whitepoint: [0.1, 0.18, 0.5, 0.9167].map((c) =>
      whitepointTonemap(c, config.wp_gain, config.wp, config.wp_gamma, 1),
    ),
  },
  source: Array.from(source.data),
  expected: Array.from(treated.data),
};

const target = path.join(
  process.cwd(),
  "plugins/seed-film-look/test/vectors.json",
);
writeFileSync(target, JSON.stringify(vectors), "utf8");
console.log(`wrote ${target} — ${WIDTH}x${HEIGHT}, ${vectors.expected.length} floats`);
